name: ecommerce
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  myfashion_backend_client:
    path: ../myfashion_backend_client
  serverpod_auth_idp_flutter: 3.1.1
  serverpod_flutter: 3.1.1
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.3
  font_awesome_flutter: ^10.12.0
  gap: ^3.0.1
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  intl: any
  riverpod_annotation: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    
dependency_overrides:
  flutter_secure_storage: ^10.0.0

# configuration for launcher icons
flutter_launcher_icons:
  image_path: "assets/images/logo_bg.png"
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/logo_bg.png"
  adaptive_icon_background: "#ffffff"
