name: Deploy to GCP

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PROJECT: hcdev-999
  REGION: asia-south2
  ZONE: asia-south2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        working-directory: myfashion_backend_server
        run: |
           docker build \
             -t gcr.io/${PROJECT}/serverpod-server:latest \
              .


      - name: Push Docker image
        run: |
          docker push gcr.io/${PROJECT}/serverpod-server:latest
