name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: "3.1.1"
      SERVERPOD_PASSWORD_database: "4J0f8kd_c8nBFuccs1fm8BiK0Aknb367"
      SERVERPOD_PASSWORD_redis: "td5oqGfDf3bxKI6wvtVSGvoMJeKPOkPB"

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.10.3

      - name: Start containers
        working-directory: myfashion_backend_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: myfashion_backend_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: myfashion_backend_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: myfashion_backend_server
        run: serverpod generate

      - name: Run tests
        working-directory: myfashion_backend_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: myfashion_backend_server
        run: docker compose down -v
